const EMPLOYMENT_STATUS = {
  PROBATIONARY: "PROBATIONARY",
  REGULAR: "REGULAR",
  RESIGNED: "RESIGNED",
  TERMINATED: "TERMINATED",
};

const COMPANY_DEFAULT_PROBATION_MONTHS = 6;

module.exports = { EMPLOYMENT_STATUS, COMPANY_DEFAULT_PROBATION_MONTHS };
